import re
from code_generation.tapir.paths import tapir_paths


def main():
    print(f"--- Starting definitive cleaning of {tapir_paths.RAW_TYPED_DICTS} ---")

    try:
        content = tapir_paths.RAW_TYPED_DICTS.read_text(encoding="utf-8")
    except FileNotFoundError:
        print(f"Error: {tapir_paths.RAW_TYPED_DICTS} not found. Please generate it first.")
        return

    print("Step 1: Reordering forward-referencing TypeAliases...")
    content = fix_forward_reference_aliases(content)

    print("Step 2: Assembling and formatting the final file...")
    content = assemble_final_file(content)

    tapir_paths.CLEANED_TYPED_DICTS.write_text(content, encoding="utf-8")
    print(f"✅ Successfully created final, clean TypedDict models at: {tapir_paths.CLEANED_TYPED_DICTS}")


def fix_forward_reference_aliases(content: str) -> str:
    """
    Finds patterns like `Alias: TypeAlias = list["Class"]` defined before `class Class(TypedDict)`
    and swaps them to ensure correct definition order. It also strips the quotes from the
    forward-reference, turning it into a solid runtime type to prevent Typeguard NameErrors.
    """
    pattern = re.compile(
        r"^(?P<alias_block>(?P<alias_name>\w+):\s*TypeAlias\s*=\s*list\[[\"'](?P<class_name>\w+)[\"']\](?:\n[ \t]*\"\"\"[^\"]+\"\"\")?)\n+(?P<class_block>class\s+(?P=class_name)\(TypedDict\):(?:\n(?:    .*|))*)",
        re.MULTILINE,
    )

    def replacer(match):
        alias_block = match.group("alias_block").strip()
        class_block = match.group("class_block").strip()
        class_name = match.group("class_name")

        # Changes `Hotlinks: TypeAlias = list["Hotlink"]` to `list[Hotlink]`
        alias_block = re.sub(rf'list\[["\']{class_name}["\']\]', f"list[{class_name}]", alias_block)

        print(
            f"    - Reordered '{match.group('alias_name')}' to be after '{class_name}' and stripped forward-ref quotes."
        )

        return f"{class_block}\n\n\n{alias_block}\n\n\n"

    content, num_replacements = pattern.subn(replacer, content)
    if num_replacements == 0:
        print("    - No forward-reference aliases needed reordering.")
    return content


def assemble_final_file(content: str) -> str:
    """Adds standard headers and ensures consistent double-blank line separation between definitions."""
    body_lines = [
        line for line in content.splitlines()
        if line.strip()
        and not line.strip().startswith(("#", "from __future__", "from typing", "###"))
    ]

    header = [
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal, TypeAlias, TypedDict",
        "",
        "from typing_extensions import NotRequired",
        "",
        "### This file is automatically generated and surgically cleaned. Do not edit directly. ###",
    ]

    final_content = "\n".join(header + [""] + body_lines)

    # Ensure consistent double-blank lines (\n\n\n) between definitions so that
    # the split scripts can identify class boundaries easily.
    final_content = re.sub(r'\n(class |[A-Z]\w+\s*=|[A-Z]\w+\s*:\s*TypeAlias\s*=)', r'\n\n\n\1', final_content)
    final_content = re.sub(r'\n{4,}', '\n\n\n', final_content)

    return final_content.strip() + "\n"


if __name__ == "__main__":
    main()