from __future__ import annotations
from typing import Annotated, List, TypeAlias
from pydantic import Field

from multiconn_archicad.models.base import APIModel

### This file is automatically generated and split. Do not edit directly. ###


from .types import (
    ActiveDesignOptionsInCombination,
    Angle,
    Area,
    AssociativeDimensionData,
    AssociativeDimensionOnSectionData,
    AttributeHeadersWrapper,
    AttributeIdArrayItem,
    AttributePropertyValue,
    AttributeType,
    BeamData,
    BeamWithDetails,
    BoundingBox3DArrayItem,
    BuildingMaterialDataArrayItem,
    BuildingMaterialPhysicalPropertiesArrayItem,
    ClassificationItemIdArrayItem,
    ClassificationSystemIdArrayItem,
    ClassificationSystemsWithItem,
    Collision,
    ColorRGB,
    ColumnData,
    ColumnWithDetails,
    Comment,
    CompositeDataArrayItem,
    Conflict,
    ConflictPolicy,
    ConnectedElementsWrapper,
    CutPlane,
    DatabaseIdAndWindowType,
    DatabaseIdArrayItem,
    DesignOptionAndSetPair,
    DesignOptionCombinationData,
    DesignOptionCombinationDetails,
    DesignOptionCombinationIdArrayItem,
    DesignOptionData,
    DesignOptionDetails,
    DesignOptionForElement,
    DesignOptionIdArrayItem,
    DesignOptionSet,
    DetailData,
    DetailsOfElement,
    DimensionData,
    DocumentRevision,
    DoorData,
    DoorWithDetails,
    DrawingData,
    Element,
    ElementClassification,
    ElementClassificationItemArray,
    ElementDesignOptionPair,
    ElementFilter,
    ElementGroupParameters,
    ElementIFCIds,
    ElementIFCProperties,
    ElementIFCType,
    ElementId,
    ElementIdArrayItem,
    ElementPropertyValue,
    ElementType,
    ElementsByIFCId,
    ElementsOfDesignOption,
    ElementsWithDetail,
    ElementsWithExecutionResults,
    ElementsWithGDLParameter,
    ElementsWithMoveVector,
    ElementsWithRotation,
    Error,
    ErrorItem,
    FailedExecutionResult,
    FavoritesFromElement,
    FavoritesWrapper,
    FileType,
    Format,
    GDLParameterList,
    GroupIdArrayItem,
    HighlightedColor,
    Hotlink,
    ImageType,
    Issue,
    IssueCommentStatus,
    IssueElementType,
    IssueId,
    IssueIdArrayItem,
    LabelData,
    LampData,
    LayerCombinationAttribute,
    LayerCombinationDataArrayItem,
    LayerDataArrayItem,
    LayoutData,
    Length,
    Library,
    LibraryFileAddition,
    LibraryPart,
    LibraryPartType,
    MeshData,
    Method,
    ModelViewOption,
    MorphData,
    MorphWithDetails,
    NavigatorItemIdArrayItem,
    NavigatorItemIdsWithViewSetting,
    NewClassificationItem,
    ObjectData,
    OpeningData,
    PolylineData,
    PrintArea,
    ProjectInfoField,
    ProjectInfoFieldData,
    ProjectLocation,
    PropertyDefinitionArrayItem,
    PropertyDetails,
    PropertyGroupArrayItem,
    PropertyGroupIdArrayItem,
    PropertyIdArrayItem,
    PropertyValuesArrayItem,
    RevisionChange,
    RevisionChangesArrayItem,
    RevisionIssue,
    RoofData,
    RoofWithDetails,
    SectionData,
    Settings,
    SkippedSampleItem,
    SlabData,
    SlabWithDetails,
    StoryParameters,
    StorySettings,
    Subelement,
    SubsetData,
    SuccessfulExecutionResult,
    SurfaceDataArrayItem,
    SurveyPoint,
    TextData,
    ViewSettings,
    ViewTransformations,
    Volume,
    WallData,
    WallThicknessDimensionData,
    WallWithDetails,
    WindowData,
    WindowType,
    WindowWithDetails,
    WorksheetData,
    ZoneBoundariesWrapper,
    ZoneData,
)


class GetAddOnVersionResult(APIModel):
    version: Annotated[str, Field(description='Version number in the form of "1.1.1".', min_length=1)]


class GetArchicadLocationResult(APIModel):
    archicadLocation: Annotated[
        str,
        Field(
            description="The location of the Archicad executable in the filesystem.",
            min_length=1,
        ),
    ]


QuitArchicadResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class GetCurrentWindowTypeResult(APIModel):
    currentWindowType: WindowType


ChangeWindowResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class GetProjectInfoResult(APIModel):
    isUntitled: Annotated[bool, Field(description="True, if the project is not saved yet.")]
    isTeamwork: Annotated[
        bool,
        Field(description="True, if the project is a Teamwork (BIMcloud) project."),
    ]
    projectLocation: Annotated[
        str | None,
        Field(
            description="The location of the project in the filesystem or a BIMcloud project reference.",
            min_length=1,
        ),
    ] = None
    projectPath: Annotated[
        str | None,
        Field(
            description="The path of the project. A filesystem path or a BIMcloud server relative path.",
            min_length=1,
        ),
    ] = None
    projectName: Annotated[str | None, Field(description="The name of the project.", min_length=1)] = None


class SetProjectInfoFieldParameters(APIModel):
    projectInfoId: Annotated[str, Field(description="The id of the project info field.", min_length=1)]
    projectInfoValue: Annotated[str, Field(description="The new value of the project info field.", min_length=1)]


class GetStoriesResult(APIModel):
    firstStory: Annotated[int, Field(description="First story index.")]
    lastStory: Annotated[int, Field(description="Last story index.")]
    actStory: Annotated[int, Field(description="Actual (currently visible in 2D) story index.")]
    skipNullFloor: Annotated[
        bool,
        Field(description="Floor indices above ground-floor level may start with 1 instead of 0."),
    ]
    stories: Annotated[
        list[StoryParameters],
        Field(description="A list of project stories, each with their complete parameters."),
    ]


class SetStoriesParameters(APIModel):
    stories: Annotated[
        list[StorySettings],
        Field(description="A list of story settings, used as input for creating or modifying multiple stories."),
    ]


SetStoriesResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class OpenProjectParameters(APIModel):
    projectFilePath: Annotated[str, Field(description="The target project file to open.")]


OpenProjectResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


CloseProjectResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


SaveProjectResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class GetCalculationUnitsResult(APIModel):
    length: Length
    area: Area
    volume: Volume
    angle: Angle


SetGeoLocationResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class PrintViewParameters(APIModel):
    grid: Annotated[bool | None, Field(description="Print the grid. The default is false.")] = None
    fixText: Annotated[bool | None, Field(description="Use fixed text size. The default is false.")] = None
    scale: Annotated[int | None, Field(description="Print scale. The default is 100.")] = None
    printArea: Annotated[
        PrintArea | None,
        Field(description="The area to print. The default is 'currentView'."),
    ] = None


PrintViewResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class RebuildViewParameters(APIModel):
    regenerate: Annotated[
        bool | None,
        Field(
            description="Regenerate the view. The default is false, meaning the view will not be regenerated, but rebuilt."
        ),
    ] = None


RebuildViewResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class ChangeSelectionOfElementsResult(APIModel):
    executionResultsOfAddToSelection: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]
    executionResultsOfRemoveFromSelection: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class SetDetailsOfElementsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class Get3DBoundingBoxesResult(APIModel):
    boundingBoxes3D: Annotated[
        list[BoundingBox3DArrayItem | ErrorItem],
        Field(description="A list of 3D bounding boxes."),
    ]


HighlightElementsResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class MoveElementsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class RotateElementsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


DeleteElementsResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


LockElementsResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


UnlockElementsResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class SetGDLParametersOfElementsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class ModifyWallsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class ModifyBeamsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class ModifySlabsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class ModifyColumnsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class ModifyWindowsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class ModifyDoorsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class ModifyMorphsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class ModifyRoofsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class GetElementPreviewImageResult(APIModel):
    previewImage: Annotated[str, Field(description="The base64 encoded preview image.")]


class GetRoomImageResult(APIModel):
    roomImage: Annotated[str, Field(description="The base64 encoded room image.")]


class SetElementNotificationClientParameters(APIModel):
    host: Annotated[
        str | None,
        Field(description="The host address of the notification client. If not provided, localhost is used."),
    ] = None
    port: Annotated[int, Field(description="The port number of the notification client.")]
    notifyOnNewElement: Annotated[
        bool | None,
        Field(description="Notify on creation of a new element. Optional parameter, by default true."),
    ] = None
    notifyOnModificationOfAnElement: Annotated[
        bool | None,
        Field(description="Notify on modification/deletion of an element. Optional parameter, by default true."),
    ] = None
    notifyOnReservationChanges: Annotated[
        bool | None,
        Field(description="Notify on reservation changes of an element. Optional parameter, by default true."),
    ] = None


SetElementNotificationClientResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class RemoveElementNotificationClientParameters(APIModel):
    host: Annotated[
        str | None,
        Field(description="The host address of the notification client. If not provided, localhost is used."),
    ] = None
    port: Annotated[int, Field(description="The port number of the notification client.")]


RemoveElementNotificationClientResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class CreateGroupsResult(APIModel):
    groupGuids: Annotated[
        list[GroupIdArrayItem | ErrorItem],
        Field(description="The results of the group creation operations."),
    ]


class GetFavoritesByTypeParameters(APIModel):
    elementType: ElementType


GetFavoritesByTypeResult: TypeAlias = FavoritesWrapper | ErrorItem


class GetFavoritePreviewImageParameters(APIModel):
    favorite: Annotated[str, Field(description="The name of the favorite.")]
    imageType: Annotated[
        ImageType | None,
        Field(description="The type of the preview image. Default is 3D."),
    ] = None
    format: Annotated[Format | None, Field(description="The image format. Default is png.")] = None
    width: Annotated[
        int | None,
        Field(description="The width of the preview image in pixels. Default is 128."),
    ] = None
    height: Annotated[
        int | None,
        Field(description="The height of the preview image in pixels. Default is 128."),
    ] = None


class GetFavoritePreviewImageResult(APIModel):
    previewImage: Annotated[str, Field(description="The base64 encoded preview image.")]


class ApplyFavoritesToElementDefaultsParameters(APIModel):
    favorites: Annotated[list[str], Field(description="A list of favorite names")]


class ApplyFavoritesToElementDefaultsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class CreateFavoritesFromElementsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class ImportFavoritesParameters(APIModel):
    path: Annotated[
        str,
        Field(description="Absolute path on the AC host to a Favorites file (.prefs) or folder."),
    ]
    targetFolder: Annotated[
        list[str] | None,
        Field(description="Folder hierarchy under which to import. Empty = root."),
    ] = None
    importFolders: Annotated[
        bool | None,
        Field(description="If true and `path` is a folder, the folder structure is preserved."),
    ] = None
    conflictPolicy: Annotated[
        ConflictPolicy | None,
        Field(description="How to resolve name conflicts. Default Overwrite."),
    ] = None


class ImportFavoritesResult(APIModel):
    firstConflictName: Annotated[
        str | None,
        Field(description="Set when conflictPolicy=Error and a name collided; absent otherwise."),
    ] = None


class ExportFavoritesParameters(APIModel):
    path: Annotated[
        str,
        Field(
            description="Absolute path on the AC host. If extension matches the Favorite binary format (.prefs), writes a single file; otherwise treats as folder."
        ),
    ]
    names: Annotated[
        list[str] | None,
        Field(description="Optional subset of Favorites to export. Default: export all."),
    ] = None


class GetAllPropertiesResult(APIModel):
    properties: Annotated[list[PropertyDetails], Field(description="A list of property identifiers.")]


class GetPropertyValuesOfElementsResult(APIModel):
    propertyValuesForElements: Annotated[
        list[PropertyValuesArrayItem | ErrorItem],
        Field(
            description="List of property value lists. The order of the outer list is that of the given elements. The order of the inner lists are that of the given properties."
        ),
    ]


class SetPropertyValuesOfElementsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class GetPropertyValuesOfAttributesResult(APIModel):
    propertyValuesForAttributes: Annotated[
        list[PropertyValuesArrayItem | ErrorItem],
        Field(
            description="List of property value lists. The order of the outer list is that of the given attributes. The order of the inner lists are that of the given properties."
        ),
    ]


class SetPropertyValuesOfAttributesResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class CreatePropertyGroupsParameters(APIModel):
    propertyGroups: Annotated[
        list[PropertyGroupArrayItem],
        Field(description="The parameters of the new property groups."),
    ]


class CreatePropertyGroupsResult(APIModel):
    propertyGroupIds: Annotated[
        list[PropertyGroupIdArrayItem],
        Field(description="The identifiers of the created property groups."),
    ]


class DeletePropertyGroupsParameters(APIModel):
    propertyGroupIds: Annotated[
        list[PropertyGroupIdArrayItem],
        Field(description="The identifiers of property groups to delete."),
    ]


class DeletePropertyGroupsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class CreatePropertyDefinitionsResult(APIModel):
    propertyIds: Annotated[
        list[PropertyIdArrayItem | ErrorItem],
        Field(description="A list of property identifiers."),
    ]


class DeletePropertyDefinitionsParameters(APIModel):
    propertyIds: Annotated[
        list[PropertyIdArrayItem],
        Field(description="The identifiers of properties to delete."),
    ]


class DeletePropertyDefinitionsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class GetClassificationsOfElementsResult(APIModel):
    elementClassifications: Annotated[
        list[ElementClassificationItemArray | ErrorItem],
        Field(
            description="The list of element classification item identifiers. Order of the ids are the same as in the input. Non-existing elements or non-existing classification systems are represented by error objects."
        ),
    ]


class SetClassificationsOfElementsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class CreateClassificationSystemsParameters(APIModel):
    classificationSystemsWithItems: Annotated[
        list[ClassificationSystemsWithItem],
        Field(description="Classification systems with items."),
    ]


class CreateClassificationSystemsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class CreateClassificationItemsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class DeleteClassificationSystemsParameters(APIModel):
    classificationSystemIds: Annotated[
        list[ClassificationSystemIdArrayItem],
        Field(description="A list of classification system identifiers."),
    ]


class DeleteClassificationSystemsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class DeleteClassificationItemsParameters(APIModel):
    classificationItemIds: Annotated[
        list[ClassificationItemIdArrayItem],
        Field(description="A list of classification item identifiers."),
    ]


class DeleteClassificationItemsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class GetAttributesByTypeParameters(APIModel):
    attributeType: AttributeType


class IFCFileOperationParameters(APIModel):
    method: Annotated[Method, Field(description="The file operation method to use.")]
    ifcFilePath: Annotated[str, Field(description="The target IFC file to use.")]
    fileType: Annotated[
        FileType | None,
        Field(description="The type of the IFC file. The default is 'ifc'."),
    ] = None


IFCFileOperationResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class GetElementsByIFCIdsParameters(APIModel):
    ifcIds: Annotated[
        list[str],
        Field(description="A list of IFC identifiers to get the corresponding elements for."),
    ]


class GetLibrariesResult(APIModel):
    libraries: Annotated[list[Library], Field(description="A list of project libraries.")]


ReloadLibrariesResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class AddFilesToEmbeddedLibraryResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class GetAvailableLibraryPartsParameters(APIModel):
    filterByTypeId: Annotated[
        LibraryPartType | None,
        Field(description="Optional. Filter by libpart type (matches the value returned by LibPartTypeIdToString)."),
    ] = None


class GetAvailableLibraryPartsResult(APIModel):
    libraryParts: list[LibraryPart]
    skippedCount: Annotated[
        int,
        Field(
            description="Library parts that ACAPI_LibraryPart_Get failed to read. Non-zero means the inventory is partial."
        ),
    ]
    skippedSample: Annotated[
        list[SkippedSampleItem] | None,
        Field(description="First five failed indices with their ACAPI error code, for diagnostic."),
    ] = None


TeamworkSendResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


TeamworkReceiveResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


ReleaseElementsResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


UpdateDrawingsResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class CreateSubsetsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class GetModelViewOptionsResult(APIModel):
    modelViewOptions: list[ModelViewOption]


class SetViewSettingsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class Set3DCutPlanesParameters(APIModel):
    cutPlanes: Annotated[list[CutPlane] | None, Field(min_length=1)] = None


Set3DCutPlanesResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


FitInWindowResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class CreateIssueParameters(APIModel):
    name: Annotated[str, Field(description="The name of the issue.")]
    parentIssueId: IssueId | None = None
    tagText: Annotated[str | None, Field(description="Tag text of the issue, optional.")] = None


class CreateIssueResult(APIModel):
    issueId: IssueId


class DeleteIssueParameters(APIModel):
    issueId: IssueId
    acceptAllElements: Annotated[
        bool | None,
        Field(description="Accept all creation/deletion/modification of the deleted issue. By default false."),
    ] = None


DeleteIssueResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class AddCommentToIssueParameters(APIModel):
    issueId: IssueId
    author: Annotated[str | None, Field(description="The author of the new comment.")] = None
    status: IssueCommentStatus | None = None
    text: Annotated[str, Field(description="Comment text to add.")]


AddCommentToIssueResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class GetCommentsFromIssueParameters(APIModel):
    issueId: IssueId


class GetCommentsFromIssueResult(APIModel):
    comments: Annotated[list[Comment], Field(description="A list of existing comments.")]


AttachElementsToIssueResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


DetachElementsFromIssueResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class GetElementsAttachedToIssueParameters(APIModel):
    issueId: IssueId
    type: IssueElementType


class ExportIssuesToBCFParameters(APIModel):
    issues: Annotated[
        list[IssueIdArrayItem] | None,
        Field(description="Leave it empty to export all issues."),
    ] = None
    exportPath: Annotated[str, Field(description="The os path to the bcf file, including it's name.")]
    useExternalId: Annotated[
        bool,
        Field(description="Use external IFC ID or Archicad IFC ID as referenced in BCF topics."),
    ]
    alignBySurveyPoint: Annotated[
        bool,
        Field(description="Align BCF views by Archicad Survey Point or Archicad Project Origin."),
    ]


ExportIssuesToBCFResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class ImportIssuesFromBCFParameters(APIModel):
    importPath: Annotated[str, Field(description="The os path to the bcf file, including it's name.")]
    alignBySurveyPoint: Annotated[
        bool,
        Field(description="Align BCF views by Archicad Survey Point or Archicad Project Origin."),
    ]


ImportIssuesFromBCFResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class GetRevisionIssuesResult(APIModel):
    revisionIssues: list[RevisionIssue]


class GetRevisionChangesResult(APIModel):
    revisionChanges: list[RevisionChange]


class GetDocumentRevisionsResult(APIModel):
    documentRevisions: list[DocumentRevision]


class GetCurrentRevisionChangesOfLayoutsResult(APIModel):
    currentRevisionChangesOfLayouts: RevisionChangesArrayItem | ErrorItem


class GetRevisionChangesOfElementsResult(APIModel):
    revisionChangesOfElements: RevisionChangesArrayItem | ErrorItem


class CreateDesignOptionSetsParameters(APIModel):
    designOptionSets: list[str]


class CreateDesignOptionSetsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class SetActiveDesignOptionsInCombinationsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class MoveElementsToDesignOptionsResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class MoveDesignOptionsToAnotherSetResult(APIModel):
    executionResults: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult],
        Field(description="A list of execution results."),
    ]


class GenerateDocumentationParameters(APIModel):
    destinationFolder: Annotated[
        str,
        Field(
            description="Destination folder for the generated documentation files.",
            min_length=1,
        ),
    ]


GenerateDocumentationResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult


class GetProjectInfoFieldsResult(APIModel):
    fields: Annotated[list[ProjectInfoField], Field(description="A list of project info fields.")]


class CreateProjectInfoFieldsParameters(APIModel):
    projectInfoFields: Annotated[
        list[ProjectInfoFieldData],
        Field(description="Array of custom project info fields to create."),
    ]


class CreateProjectInfoFieldsResult(APIModel):
    fields: Annotated[list[ProjectInfoField], Field(description="A list of project info fields.")]


class GetGeoLocationResult(APIModel):
    projectLocation: ProjectLocation
    surveyPoint: SurveyPoint


class SetGeoLocationParameters(APIModel):
    projectLocation: ProjectLocation | None = None
    surveyPoint: SurveyPoint | None = None


class SetDetailsOfElementsParameters(APIModel):
    elementsWithDetails: Annotated[list[ElementsWithDetail], Field(description="The elements with parameters.")]


class GetZoneBoundariesParameters(APIModel):
    zoneElementId: ElementId


GetZoneBoundariesResult: TypeAlias = ZoneBoundariesWrapper | ErrorItem


class GetCollisionsResult(APIModel):
    collisions: list[Collision]


class MoveElementsParameters(APIModel):
    elementsWithMoveVectors: Annotated[
        list[ElementsWithMoveVector],
        Field(description="The elements with move vector pairs."),
    ]


class RotateElementsParameters(APIModel):
    elementsWithRotations: Annotated[
        list[ElementsWithRotation],
        Field(description="The elements with rotation settings."),
    ]


class GetGDLParametersOfElementsResult(APIModel):
    gdlParametersOfElements: Annotated[list[GDLParameterList], Field(description="The GDL parameters of elements.")]


class SetGDLParametersOfElementsParameters(APIModel):
    elementsWithGDLParameters: Annotated[
        list[ElementsWithGDLParameter],
        Field(description="The elements with GDL parameters dictionary pairs."),
    ]


class CreateColumnsParameters(APIModel):
    columnsData: Annotated[list[ColumnData], Field(description="Array of data to create Columns.")]


class CreateBeamsParameters(APIModel):
    beamsData: list[BeamData]


class CreateStairsParameters(APIModel):
    stairsData: Annotated[list[SectionData], Field(description="Array of data to create Stair elements.")]


class CreateSlabsParameters(APIModel):
    slabsData: Annotated[list[SlabData], Field(description="Array of data to create Slabs.")]


class GetDimensionDataParameters(APIModel):
    elements: Annotated[list[Element], Field(description="The identifier of the dimension elements.")]


class CreatePolylinesParameters(APIModel):
    polylinesData: Annotated[list[PolylineData], Field(description="Array of data to create Polylines.")]


class CreateObjectsParameters(APIModel):
    objectsData: Annotated[list[ObjectData], Field(description="Array of data to create Objects.")]


class CreateLampsParameters(APIModel):
    lampsData: Annotated[list[LampData], Field(description="Array of data to create Lamps.")]


class CreateMeshesParameters(APIModel):
    meshesData: Annotated[list[MeshData], Field(description="Array of data to create Meshes.")]


class CreateTextsParameters(APIModel):
    textsData: Annotated[list[TextData], Field(description="Array of data to create Texts.")]


class GetElementPreviewImageParameters(APIModel):
    elementId: ElementId
    imageType: Annotated[
        ImageType | None,
        Field(description="The type of the preview image. Default is 3D."),
    ] = None
    format: Annotated[Format | None, Field(description="The image format. Default is png.")] = None
    width: Annotated[
        int | None,
        Field(description="The width of the preview image in pixels. Default is 128."),
    ] = None
    height: Annotated[
        int | None,
        Field(description="The height of the preview image in pixels. Default is 128."),
    ] = None


class GetRoomImageParameters(APIModel):
    zoneId: ElementId
    format: Annotated[Format | None, Field(description="The image format. Default is png.")] = None
    width: Annotated[
        int | None,
        Field(description="The width of the preview image in pixels. Default is 256."),
    ] = None
    height: Annotated[
        int | None,
        Field(description="The height of the preview image in pixels. Default is 256."),
    ] = None
    offset: Annotated[
        float | None,
        Field(description="Offset of the clip polygon from the edge of the zone. Default is 0.001."),
    ] = None
    scale: Annotated[
        float | None,
        Field(description="Scale of the view (e.g. 0.005 for 1:200). Default is 0.005."),
    ] = None
    backgroundColor: Annotated[
        ColorRGB | None,
        Field(description="Background color of the generated image. Default is white (1.0, 1.0, 1.0)."),
    ] = None


class CreateFavoritesFromElementsParameters(APIModel):
    favoritesFromElements: list[FavoritesFromElement]


class SetPropertyValuesOfElementsParameters(APIModel):
    elementPropertyValues: Annotated[
        list[ElementPropertyValue],
        Field(description="A list of element property values."),
    ]


class SetPropertyValuesOfAttributesParameters(APIModel):
    attributePropertyValues: Annotated[
        list[AttributePropertyValue],
        Field(description="A list of attribute property values."),
    ]


class CreatePropertyDefinitionsParameters(APIModel):
    propertyDefinitions: Annotated[
        list[PropertyDefinitionArrayItem],
        Field(description="The parameters of the new properties."),
    ]


class SetClassificationsOfElementsParameters(APIModel):
    elementClassifications: Annotated[
        list[ElementClassification],
        Field(description="A list of element classification identifiers."),
    ]


class CreateClassificationItemsParameters(APIModel):
    newClassificationItems: Annotated[
        list[NewClassificationItem],
        Field(description="Classification systems with items."),
    ]


GetAttributesByTypeResult: TypeAlias = AttributeHeadersWrapper | ErrorItem


class CreateLayersParameters(APIModel):
    layerDataArray: Annotated[
        list[LayerDataArrayItem],
        Field(description="Array of data to create new Layers."),
    ]
    overwriteExisting: Annotated[
        bool | None,
        Field(
            description="Overwrite the Layer if exists with the same name, or if index is given with the same index. The default is false."
        ),
    ] = None


class CreateLayerCombinationsParameters(APIModel):
    layerCombinationDataArray: Annotated[
        list[LayerCombinationDataArrayItem],
        Field(description="Array of data to create new Layer Combinations."),
    ]
    overwriteExisting: Annotated[
        bool | None,
        Field(
            description="Overwrite the Layer Combination if exists with the same guid/index/name. The default is false."
        ),
    ] = None


class CreateBuildingMaterialsParameters(APIModel):
    buildingMaterialDataArray: Annotated[
        list[BuildingMaterialDataArrayItem],
        Field(description="Array of data to create new Building Materials."),
    ]
    overwriteExisting: Annotated[
        bool | None,
        Field(
            description="Overwrite the Building Material if exists with the same name, or if index is given with the same index. The default is false."
        ),
    ] = None


class GetLayerCombinationsResult(APIModel):
    layerCombinations: Annotated[
        list[LayerCombinationAttribute | ErrorItem],
        Field(description="A list of layer combinations."),
    ]


class GetIFCIdsOfElementsResult(APIModel):
    elementIFCIds: Annotated[
        list[ElementIFCIds | ErrorItem],
        Field(description="A list of the IFC identifiers of elements or errors."),
    ]


class GetIFCTypeOfElementsResult(APIModel):
    elementIFCTypes: Annotated[
        list[ElementIFCType | ErrorItem],
        Field(description="A list of the IFC types of elements or errors."),
    ]


class GetIFCPropertiesOfElementsResult(APIModel):
    elementIFCProperties: Annotated[
        list[ElementIFCProperties | ErrorItem],
        Field(description="A list of the IFC properties of elements or errors."),
    ]


class ReserveElementsResult(APIModel):
    executionResult: Annotated[
        SuccessfulExecutionResult | FailedExecutionResult,
        Field(description="The result of the execution."),
    ]
    conflicts: list[Conflict] | None = None


class CreateDetailsParameters(APIModel):
    detailsData: list[DetailData]


class CreateWorksheetsParameters(APIModel):
    worksheetsData: list[WorksheetData]


class CreateLayoutsParameters(APIModel):
    layoutsData: list[LayoutData]


class CreateSubsetsParameters(APIModel):
    subsetsData: list[SubsetData]


class CreateDrawingsParameters(APIModel):
    drawingsData: list[DrawingData]


class GetViewSettingsResult(APIModel):
    viewSettings: list[ViewSettings | ErrorItem]


class SetViewSettingsParameters(APIModel):
    navigatorItemIdsWithViewSettings: list[NavigatorItemIdsWithViewSetting]


class GetView2DTransformationsResult(APIModel):
    transformations: list[ViewTransformations | ErrorItem]


class CreateSectionsParameters(APIModel):
    sectionsData: list[SectionData]


class GetIssuesResult(APIModel):
    issues: Annotated[list[Issue], Field(description="A list of existing issues.")]


class GetDesignOptionsResult(APIModel):
    designOptions: list[DesignOptionDetails]


class GetDesignOptionSetsResult(APIModel):
    designOptionSets: list[DesignOptionSet]


class GetElementsOfDesignOptionsParameters(APIModel):
    designOptions: list[DesignOptionIdArrayItem]


class GetDesignOptionForElementsResult(APIModel):
    designOptionForElements: list[DesignOptionForElement]


class CreateDesignOptionsParameters(APIModel):
    designOptions: list[DesignOptionData]


class CreateDesignOptionsResult(APIModel):
    designOptionIdsOrErrors: Annotated[
        list[DesignOptionIdArrayItem | ErrorItem],
        Field(description="A list of design option identifiers or errors."),
    ]


class CreateDesignOptionCombinationsResult(APIModel):
    designOptionCombinationIdsOrErrors: Annotated[
        list[DesignOptionCombinationIdArrayItem | ErrorItem],
        Field(description="A list of design option combination identifiers or errors."),
    ]


class SetActiveDesignOptionsInCombinationsParameters(APIModel):
    activeDesignOptionsInCombinations: list[ActiveDesignOptionsInCombination]


class MoveElementsToDesignOptionsParameters(APIModel):
    elementDesignOptionPairs: list[ElementDesignOptionPair]


class MoveDesignOptionsToAnotherSetParameters(APIModel):
    designOptionAndSetPairs: list[DesignOptionAndSetPair]


ChangeWindowParameters: TypeAlias = NavigatorItemIdArrayItem | DatabaseIdAndWindowType


class GetElementsByTypeParameters(APIModel):
    elementType: ElementType
    filters: Annotated[list[ElementFilter] | None, Field(min_length=1)] = None
    databases: Annotated[
        list[DatabaseIdArrayItem] | None,
        Field(description="A list of Archicad databases."),
    ] = None


class GetAllElementsParameters(APIModel):
    filters: Annotated[list[ElementFilter] | None, Field(min_length=1)] = None
    databases: Annotated[
        list[DatabaseIdArrayItem] | None,
        Field(description="A list of Archicad databases."),
    ] = None


class GetDetailsOfElementsResult(APIModel):
    detailsOfElements: list[DetailsOfElement]


class CreateWallsParameters(APIModel):
    wallsData: list[WallData]


class CreateWindowsParameters(APIModel):
    windowsData: list[WindowData]


class CreateDoorsParameters(APIModel):
    doorsData: list[DoorData]


class CreateOpeningsParameters(APIModel):
    openingsData: list[OpeningData]


class CreateMorphsParameters(APIModel):
    morphsData: list[MorphData]


class CreateRoofsParameters(APIModel):
    roofsData: list[RoofData]


class CreateAssociativeDimensionsOnSectionParameters(APIModel):
    dimensionsData: list[AssociativeDimensionOnSectionData]


class CreateWallThicknessDimensionsParameters(APIModel):
    dimensionsData: list[WallThicknessDimensionData]


class GetDimensionDataResult(APIModel):
    dimensionsData: list[DimensionData | ErrorItem]


class CreateZonesParameters(APIModel):
    zonesData: Annotated[list[ZoneData], Field(description="Array of data to create Zones.")]


class CreateLabelsParameters(APIModel):
    labelsData: Annotated[list[LabelData], Field(description="Array of data to create Labels.")]


class ModifyWallsParameters(APIModel):
    wallsWithDetails: list[WallWithDetails]


class ModifyBeamsParameters(APIModel):
    beamsWithDetails: list[BeamWithDetails]


class ModifySlabsParameters(APIModel):
    slabsWithDetails: list[SlabWithDetails]


class ModifyColumnsParameters(APIModel):
    columnsWithDetails: list[ColumnWithDetails]


class ModifyWindowsParameters(APIModel):
    windowsWithDetails: list[WindowWithDetails]


class ModifyDoorsParameters(APIModel):
    doorsWithDetails: list[DoorWithDetails]


class ModifyMorphsParameters(APIModel):
    morphsWithDetails: list[MorphWithDetails]


class ModifyRoofsParameters(APIModel):
    roofsWithDetails: list[RoofWithDetails]


class CreateGroupsParameters(APIModel):
    elementGroups: Annotated[
        list[ElementGroupParameters],
        Field(description="A list of element groups to create."),
    ]


class CreateCompositesParameters(APIModel):
    compositeDataArray: Annotated[
        list[CompositeDataArrayItem],
        Field(description="Array of data to create Composites."),
    ]
    overwriteExisting: Annotated[
        bool | None,
        Field(
            description="Overwrite the Composite if exists with the same name, or if index is given with the same index. The default is false."
        ),
    ] = None


class CreateSurfacesParameters(APIModel):
    surfaceDataArray: Annotated[
        list[SurfaceDataArrayItem],
        Field(description="Array of data to create new surfaces."),
    ]
    overwriteExisting: Annotated[
        bool | None,
        Field(
            description="Overwrite the Surface if exists with the same name, or if index is given with the same index. The default is false."
        ),
    ] = None


class GetBuildingMaterialPhysicalPropertiesResult(APIModel):
    properties: Annotated[
        list[BuildingMaterialPhysicalPropertiesArrayItem],
        Field(description="A list of building material physical properties"),
    ]


class GetElementsByIFCIdsResult(APIModel):
    elementsByIFCIds: Annotated[
        list[ElementsByIFCId],
        Field(description="A list of elements identified by their IFC identifiers or errors."),
    ]


class AddFilesToEmbeddedLibraryParameters(APIModel):
    files: Annotated[
        list[LibraryFileAddition],
        Field(description="A list of library file additions to the embedded library"),
    ]


class PublishPublisherSetParameters(APIModel):
    publisherSetName: Annotated[str, Field(description="The name of the publisher set.", min_length=1)]
    outputPath: Annotated[
        str | None,
        Field(
            description="Full local or LAN path for publishing. Optional, by default the path set in the settings of the publisher set will be used.",
            min_length=1,
        ),
    ] = None
    selectedNavigatorItemIds: Annotated[
        list[NavigatorItemIdArrayItem] | None,
        Field(description="Optional publisher-tree navigator items to publish instead of the whole publisher set."),
    ] = None


class GetDatabaseIdFromNavigatorItemIdParameters(APIModel):
    navigatorItemIds: Annotated[
        list[NavigatorItemIdArrayItem],
        Field(description="A list of navigator item identifiers."),
    ]


class GetDatabaseIdFromNavigatorItemIdResult(APIModel):
    databases: Annotated[list[DatabaseIdArrayItem], Field(description="A list of Archicad databases.")]


class CreateDetailsResult(APIModel):
    databases: Annotated[list[DatabaseIdArrayItem], Field(description="A list of Archicad databases.")]


class CreateWorksheetsResult(APIModel):
    databases: Annotated[list[DatabaseIdArrayItem], Field(description="A list of Archicad databases.")]


class CreateLayoutsResult(APIModel):
    databases: Annotated[list[DatabaseIdArrayItem], Field(description="A list of Archicad databases.")]


class GetViewSettingsParameters(APIModel):
    navigatorItemIds: Annotated[
        list[NavigatorItemIdArrayItem],
        Field(description="A list of navigator item identifiers."),
    ]


class GetView2DTransformationsParameters(APIModel):
    databases: Annotated[
        list[DatabaseIdArrayItem] | None,
        Field(description="A list of Archicad databases."),
    ] = None


class GetCurrentRevisionChangesOfLayoutsParameters(APIModel):
    layoutDatabaseIds: Annotated[list[DatabaseIdArrayItem], Field(description="A list of Archicad databases.")]


class GetDesignOptionCombinationsResult(APIModel):
    designOptionCombinations: list[DesignOptionCombinationDetails]


class CreateDesignOptionCombinationsParameters(APIModel):
    designOptionCombinations: list[DesignOptionCombinationData]


class GetSelectedElementsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


GetElementsByTypeResult: TypeAlias = ElementsWithExecutionResults | ErrorItem


GetAllElementsResult: TypeAlias = ElementsWithExecutionResults | ErrorItem


class ChangeSelectionOfElementsParameters(APIModel):
    addElementsToSelection: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    removeElementsFromSelection: Annotated[
        list[ElementIdArrayItem] | None, Field(description="A list of elements.")
    ] = None


class FilterElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]
    filters: Annotated[list[ElementFilter] | None, Field(min_length=1)] = None


class FilterElementsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class GetDetailsOfElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class Get3DBoundingBoxesParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class GetSubelementsOfHierarchicalElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class GetSubelementsOfHierarchicalElementsResult(APIModel):
    subelements: list[Subelement]


class GetConnectedElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]
    connectedElementType: ElementType


GetConnectedElementsResult: TypeAlias = ConnectedElementsWrapper | ErrorItem


class GetCollisionsParameters(APIModel):
    elementsGroup1: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]
    elementsGroup2: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]
    settings: Settings | None = None


class HighlightElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]
    highlightedColors: Annotated[
        list[HighlightedColor],
        Field(description="A list of colors to highlight elements."),
    ]
    wireframe3D: Annotated[
        bool | None,
        Field(description="Optional parameter. Switch non highlighted elements in the 3D window to wireframe."),
    ] = None
    nonHighlightedColor: Annotated[
        list[int] | None,
        Field(
            description="Optional parameter. Color of the non highlighted elements as an [r, g, b, a] array. Each component must be in the 0-255 range.",
            max_length=4,
            min_length=4,
        ),
    ] = None


class DeleteElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class LockElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class UnlockElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class GetGDLParametersOfElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateColumnsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateWallsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateBeamsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateStairsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateSlabsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateWindowsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateDoorsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateOpeningsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateMorphsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateRoofsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateAssociativeDimensionsParameters(APIModel):
    dimensionsData: list[AssociativeDimensionData]


class CreateAssociativeDimensionsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateAssociativeDimensionsOnSectionResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateWallThicknessDimensionsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateZonesResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreatePolylinesResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateObjectsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateLampsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateMeshesResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateLabelsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateTextsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class GetPropertyValuesOfElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]
    properties: Annotated[list[PropertyIdArrayItem], Field(description="A list of property identifiers.")]


class GetPropertyValuesOfAttributesParameters(APIModel):
    attributeIds: Annotated[list[AttributeIdArrayItem], Field(description="A list of attributes.")]
    properties: Annotated[list[PropertyIdArrayItem], Field(description="A list of property identifiers.")]


class GetClassificationsOfElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]
    classificationSystemIds: Annotated[
        list[ClassificationSystemIdArrayItem],
        Field(description="A list of classification system identifiers."),
    ]


class CreateLayersResult(APIModel):
    attributeIds: Annotated[list[AttributeIdArrayItem], Field(description="A list of attributes.")]


class CreateLayerCombinationsResult(APIModel):
    attributeIds: Annotated[list[AttributeIdArrayItem], Field(description="A list of attributes.")]


class CreateBuildingMaterialsResult(APIModel):
    attributeIds: Annotated[list[AttributeIdArrayItem], Field(description="A list of attributes.")]


class CreateCompositesResult(APIModel):
    attributeIds: Annotated[list[AttributeIdArrayItem], Field(description="A list of attributes.")]


class CreateSurfacesResult(APIModel):
    attributeIds: Annotated[list[AttributeIdArrayItem], Field(description="A list of attributes.")]


class GetBuildingMaterialPhysicalPropertiesParameters(APIModel):
    attributeIds: Annotated[list[AttributeIdArrayItem], Field(description="A list of attributes.")]


class GetLayerCombinationsParameters(APIModel):
    attributes: Annotated[list[AttributeIdArrayItem], Field(description="A list of attributes.")]


class GetIFCIdsOfElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class GetIFCTypeOfElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class GetIFCPropertiesOfElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class ReserveElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class ReleaseElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class UpdateDrawingsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class CreateDrawingsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class FitInWindowParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None


class CreateSectionsResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class AttachElementsToIssueParameters(APIModel):
    issueId: IssueId
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]
    type: IssueElementType


class DetachElementsFromIssueParameters(APIModel):
    issueId: IssueId
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class GetElementsAttachedToIssueResult(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class GetRevisionChangesOfElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class GetElementsOfDesignOptionsResult(APIModel):
    elementsOfDesignOptions: list[ElementsOfDesignOption | ErrorItem]


class GetDesignOptionForElementsParameters(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class GetHotlinksResult(APIModel):
    hotlinks: Annotated[list[Hotlink], Field(description="A list of hotlink nodes.")]
