# This file is automatically generated by the build system.
# Do not edit this file directly.

from __future__ import annotations
from typing import TYPE_CHECKING
from pydantic import TypeAdapter

from multiconn_archicad.models.tapir.commands import (
    ChangeWindowParameters,
    ChangeWindowResult,
    GetAddOnVersionResult,
    GetArchicadLocationResult,
    GetCurrentWindowTypeResult,
    QuitArchicadResult,
)
from multiconn_archicad.models.tapir.types import (
    DatabaseIdAndWindowType,
    FailedExecutionResult,
    NavigatorItemIdArrayItem,
    SuccessfulExecutionResult,
    WindowType,
)

if TYPE_CHECKING:
    from multiconn_archicad.core.core_commands import CoreCommands


class ApplicationCommands:
    def __init__(self, core: CoreCommands):
        self._core = core

    def change_window(
        self, parameters: NavigatorItemIdArrayItem | DatabaseIdAndWindowType
    ) -> FailedExecutionResult | SuccessfulExecutionResult:
        """
        Changes the current (active) window to the given window.

        Args:
            parameters (NavigatorItemIdArrayItem | DatabaseIdAndWindowType): Union model
                configuration parameters.

        Returns:
            FailedExecutionResult | SuccessfulExecutionResult

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        validated_params = TypeAdapter(ChangeWindowParameters).validate_python(parameters)
        response_dict = self._core.post_tapir_command(
            "ChangeWindow", validated_params.model_dump(mode="json", by_alias=True, exclude_none=True)
        )
        validated_response = TypeAdapter(ChangeWindowResult).validate_python(response_dict)
        return validated_response

    def get_add_on_version(self) -> str:
        """
        Retrieves the version of the Tapir Additional JSON Commands Add-On.

        Returns:
            str: Version number in the form of "1.1.1".

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        response_dict = self._core.post_tapir_command("GetAddOnVersion")
        validated_response = GetAddOnVersionResult.model_validate(response_dict)
        return validated_response.version

    def get_archicad_location(self) -> str:
        """
        Retrieves the location of the currently running Archicad executable.

        Returns:
            str: The location of the Archicad executable in the filesystem.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        response_dict = self._core.post_tapir_command("GetArchicadLocation")
        validated_response = GetArchicadLocationResult.model_validate(response_dict)
        return validated_response.archicadLocation

    def get_current_window_type(self) -> WindowType:
        """
        Returns the type of the current (active) window.

        Returns:
            WindowType

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        response_dict = self._core.post_tapir_command("GetCurrentWindowType")
        validated_response = GetCurrentWindowTypeResult.model_validate(response_dict)
        return validated_response.currentWindowType

    def quit_archicad(self) -> FailedExecutionResult | SuccessfulExecutionResult:
        """
        Performs a quit operation on the currently running Archicad instance.

        Returns:
            FailedExecutionResult | SuccessfulExecutionResult

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        response_dict = self._core.post_tapir_command("QuitArchicad")
        validated_response = TypeAdapter(QuitArchicadResult).validate_python(response_dict)
        return validated_response
