# This file is automatically generated by the build system.
# Do not edit this file directly.

from __future__ import annotations
from typing import TYPE_CHECKING

from multiconn_archicad.models.tapir.commands import (
    ChangeSelectionOfElementsParameters,
    ChangeSelectionOfElementsResult,
    CreateColumnsParameters,
    CreateColumnsResult,
    CreateMeshesParameters,
    CreateMeshesResult,
    CreateObjectsParameters,
    CreateObjectsResult,
    CreatePolylinesParameters,
    CreatePolylinesResult,
    CreateSlabsParameters,
    CreateSlabsResult,
    CreateZonesParameters,
    CreateZonesResult,
    DeleteElementsParameters,
    FilterElementsParameters,
    FilterElementsResult,
    Get3DBoundingBoxesParameters,
    Get3DBoundingBoxesResult,
    GetAllElementsParameters,
    GetAllElementsResult,
    GetClassificationsOfElementsParameters,
    GetClassificationsOfElementsResult,
    GetCollisionsParameters,
    GetCollisionsResult,
    GetConnectedElementsParameters,
    GetConnectedElementsResult,
    GetDetailsOfElementsParameters,
    GetDetailsOfElementsResult,
    GetElementsByTypeParameters,
    GetElementsByTypeResult,
    GetGDLParametersOfElementsParameters,
    GetGDLParametersOfElementsResult,
    GetSelectedElementsResult,
    GetSubelementsOfHierarchicalElementsParameters,
    GetSubelementsOfHierarchicalElementsResult,
    GetZoneBoundariesParameters,
    GetZoneBoundariesResult,
    HighlightElementsParameters,
    MoveElementsParameters,
    MoveElementsResult,
    SetClassificationsOfElementsParameters,
    SetClassificationsOfElementsResult,
    SetDetailsOfElementsParameters,
    SetDetailsOfElementsResult,
    SetGDLParametersOfElementsParameters,
    SetGDLParametersOfElementsResult,
)
from multiconn_archicad.models.tapir.types import (
    ClassificationSystemIdArrayItem,
    ColumnsDatum,
    DatabaseIdArrayItem,
    ElementClassification,
    ElementFilter,
    ElementId,
    ElementIdArrayItem,
    ElementType,
    ElementsWithDetail,
    ElementsWithGDLParameter,
    ElementsWithMoveVector,
    HighlightedColor,
    MeshesDatum,
    ObjectsDatum,
    PolylinesDatum,
    Settings,
    SlabsDatum,
    ZonesDatum,
)

if TYPE_CHECKING:
    from multiconn_archicad.core.core_commands import CoreCommands


class ElementCommands:
    def __init__(self, core: CoreCommands):
        self._core = core

    def change_selection_of_elements(
        self,
        add_elements_to_selection: list[ElementIdArrayItem] | None = None,
        remove_elements_from_selection: list[ElementIdArrayItem] | None = None,
    ) -> ChangeSelectionOfElementsResult:
        """
        Adds/removes a number of elements to/from the current selection.

        Args:
            add_elements_to_selection (list[ElementIdArrayItem] | None): A list of elements.
            remove_elements_from_selection (list[ElementIdArrayItem] | None): A list of
                elements.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "addElementsToSelection": add_elements_to_selection,
            "removeElementsFromSelection": remove_elements_from_selection,
        }
        validated_params = ChangeSelectionOfElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "ChangeSelectionOfElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return ChangeSelectionOfElementsResult.model_validate(response_dict)

    def create_columns(self, columns_data: list[ColumnsDatum]) -> CreateColumnsResult:
        """
        Creates Column elements based on the given parameters.

        Args:
            columns_data (list[ColumnsDatum]): Array of data to create Columns.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "columnsData": columns_data,
        }
        validated_params = CreateColumnsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "CreateColumns",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return CreateColumnsResult.model_validate(response_dict)

    def create_meshes(self, meshes_data: list[MeshesDatum]) -> CreateMeshesResult:
        """
        Creates Mesh elements based on the given parameters.

        Args:
            meshes_data (list[MeshesDatum]): Array of data to create Meshes.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "meshesData": meshes_data,
        }
        validated_params = CreateMeshesParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "CreateMeshes",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return CreateMeshesResult.model_validate(response_dict)

    def create_objects(self, objects_data: list[ObjectsDatum]) -> CreateObjectsResult:
        """
        Creates Object elements based on the given parameters.

        Args:
            objects_data (list[ObjectsDatum]): Array of data to create Objects.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "objectsData": objects_data,
        }
        validated_params = CreateObjectsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "CreateObjects",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return CreateObjectsResult.model_validate(response_dict)

    def create_polylines(self, polylines_data: list[PolylinesDatum]) -> CreatePolylinesResult:
        """
        Creates Polyline elements based on the given parameters.

        Args:
            polylines_data (list[PolylinesDatum]): Array of data to create Polylines.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "polylinesData": polylines_data,
        }
        validated_params = CreatePolylinesParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "CreatePolylines",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return CreatePolylinesResult.model_validate(response_dict)

    def create_slabs(self, slabs_data: list[SlabsDatum]) -> CreateSlabsResult:
        """
        Creates Slab elements based on the given parameters.

        Args:
            slabs_data (list[SlabsDatum]): Array of data to create Slabs.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "slabsData": slabs_data,
        }
        validated_params = CreateSlabsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "CreateSlabs",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return CreateSlabsResult.model_validate(response_dict)

    def create_zones(self, zones_data: list[ZonesDatum]) -> CreateZonesResult:
        """
        Creates Zone elements based on the given parameters.

        Args:
            zones_data (list[ZonesDatum]): Array of data to create Zones.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "zonesData": zones_data,
        }
        validated_params = CreateZonesParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "CreateZones",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return CreateZonesResult.model_validate(response_dict)

    def delete_elements(self, elements: list[ElementIdArrayItem]) -> None:
        """
        Deletes elements.

        Args:
            elements (list[ElementIdArrayItem]): A list of elements.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elements": elements,
        }
        validated_params = DeleteElementsParameters(**params_dict)
        self._core.post_tapir_command(
            "DeleteElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return None

    def filter_elements(
        self,
        elements: list[ElementIdArrayItem],
        filters: list[ElementFilter] | None = None,
    ) -> FilterElementsResult:
        """
        Tests an elements by the given criterias.

        Args:
            elements (list[ElementIdArrayItem]): A list of elements.
            filters (list[ElementFilter] | None) (Constraints: min_length=1)

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elements": elements,
            "filters": filters,
        }
        validated_params = FilterElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "FilterElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return FilterElementsResult.model_validate(response_dict)

    def get_3d_bounding_boxes(self, elements: list[ElementIdArrayItem]) -> Get3DBoundingBoxesResult:
        """
        Get the 3D bounding box of elements. The bounding box is calculated from the global
        origin in the 3D view. The output is the array of the bounding boxes respective to the
        input array of elements.

        Args:
            elements (list[ElementIdArrayItem]): A list of elements.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elements": elements,
        }
        validated_params = Get3DBoundingBoxesParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "Get3DBoundingBoxes",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return Get3DBoundingBoxesResult.model_validate(response_dict)

    def get_all_elements(
        self,
        filters: list[ElementFilter] | None = None,
        databases: list[DatabaseIdArrayItem] | None = None,
    ) -> GetAllElementsResult:
        """
        Returns the identifier of all elements on the plan. Use the optional filter parameter
        for filtering.

        Args:
            filters (list[ElementFilter] | None) (Constraints: min_length=1)
            databases (list[DatabaseIdArrayItem] | None): A list of Archicad databases.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "filters": filters,
            "databases": databases,
        }
        validated_params = GetAllElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "GetAllElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return GetAllElementsResult.model_validate(response_dict)

    def get_classifications_of_elements(
        self,
        elements: list[ElementIdArrayItem],
        classification_system_ids: list[ClassificationSystemIdArrayItem],
    ) -> GetClassificationsOfElementsResult:
        """
        Returns the classification of the given elements in the given classification systems. It
        works for subelements of hierarchal elements also.

        Args:
            elements (list[ElementIdArrayItem]): A list of elements.
            classification_system_ids (list[ClassificationSystemIdArrayItem]): A list of
                classification system identifiers.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elements": elements,
            "classificationSystemIds": classification_system_ids,
        }
        validated_params = GetClassificationsOfElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "GetClassificationsOfElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return GetClassificationsOfElementsResult.model_validate(response_dict)

    def get_collisions(
        self,
        elements_group_1: list[ElementIdArrayItem],
        elements_group_2: list[ElementIdArrayItem],
        settings: Settings | None = None,
    ) -> GetCollisionsResult:
        """
        Detect collisions between the given two groups of elements.

        Args:
            elements_group_1 (list[ElementIdArrayItem]): A list of elements.
            elements_group_2 (list[ElementIdArrayItem]): A list of elements.
            settings (Settings | None)

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elementsGroup1": elements_group_1,
            "elementsGroup2": elements_group_2,
            "settings": settings,
        }
        validated_params = GetCollisionsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "GetCollisions",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return GetCollisionsResult.model_validate(response_dict)

    def get_connected_elements(
        self,
        elements: list[ElementIdArrayItem],
        connected_element_type: ElementType,
    ) -> GetConnectedElementsResult:
        """
        Gets connected elements of the given elements.

        Args:
            elements (list[ElementIdArrayItem]): A list of elements.
            connected_element_type (ElementType)

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elements": elements,
            "connectedElementType": connected_element_type,
        }
        validated_params = GetConnectedElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "GetConnectedElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return GetConnectedElementsResult.model_validate(response_dict)

    def get_details_of_elements(self, elements: list[ElementIdArrayItem]) -> GetDetailsOfElementsResult:
        """
        Gets the details of the given elements (geometry parameters etc).

        Args:
            elements (list[ElementIdArrayItem]): A list of elements.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elements": elements,
        }
        validated_params = GetDetailsOfElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "GetDetailsOfElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return GetDetailsOfElementsResult.model_validate(response_dict)

    def get_elements_by_type(
        self,
        element_type: ElementType,
        filters: list[ElementFilter] | None = None,
        databases: list[DatabaseIdArrayItem] | None = None,
    ) -> GetElementsByTypeResult:
        """
        Returns the identifier of every element of the given type on the plan. It works for any
        type. Use the optional filter parameter for filtering.

        Args:
            element_type (ElementType)
            filters (list[ElementFilter] | None) (Constraints: min_length=1)
            databases (list[DatabaseIdArrayItem] | None): A list of Archicad databases.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elementType": element_type,
            "filters": filters,
            "databases": databases,
        }
        validated_params = GetElementsByTypeParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "GetElementsByType",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return GetElementsByTypeResult.model_validate(response_dict)

    def get_gdl_parameters_of_elements(self, elements: list[ElementIdArrayItem]) -> GetGDLParametersOfElementsResult:
        """
        Gets all the GDL parameters (name, type, value) of the given elements.

        Args:
            elements (list[ElementIdArrayItem]): A list of elements.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elements": elements,
        }
        validated_params = GetGDLParametersOfElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "GetGDLParametersOfElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return GetGDLParametersOfElementsResult.model_validate(response_dict)

    def get_selected_elements(self) -> GetSelectedElementsResult:
        """
        Gets the list of the currently selected elements.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        response_dict = self._core.post_tapir_command("GetSelectedElements")
        return GetSelectedElementsResult.model_validate(response_dict)

    def get_subelements_of_hierarchical_elements(
        self, elements: list[ElementIdArrayItem]
    ) -> GetSubelementsOfHierarchicalElementsResult:
        """
        Gets the subelements of the given hierarchical elements.

        Args:
            elements (list[ElementIdArrayItem]): A list of elements.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elements": elements,
        }
        validated_params = GetSubelementsOfHierarchicalElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "GetSubelementsOfHierarchicalElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return GetSubelementsOfHierarchicalElementsResult.model_validate(response_dict)

    def get_zone_boundaries(self, zone_element_id: ElementId) -> GetZoneBoundariesResult:
        """
        Gets the boundaries of the given Zone (connected elements, neighbour zones, etc.).

        Args:
            zone_element_id (ElementId)

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "zoneElementId": zone_element_id,
        }
        validated_params = GetZoneBoundariesParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "GetZoneBoundaries",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return GetZoneBoundariesResult.model_validate(response_dict)

    def highlight_elements(
        self,
        elements: list[ElementIdArrayItem],
        highlighted_colors: list[HighlightedColor],
        wireframe_3d: bool | None = None,
        non_highlighted_color: list[int] | None = None,
    ) -> None:
        """
        Highlights the elements given in the elements array. In case of empty elements array
        removes all previously set highlights.

        Args:
            elements (list[ElementIdArrayItem]): A list of elements.
            highlighted_colors (list[HighlightedColor]): A list of colors to highlight elements.
            wireframe_3d (bool | None): Optional parameter. Switch non highlighted elements in
                the 3D window to wireframe.
            non_highlighted_color (list[int] | None): Optional parameter. Color of the non
                highlighted elements as an [r, g, b, a] array. Each component must be in the
                0-255 range. (Constraints: max_length=4, min_length=4)

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elements": elements,
            "highlightedColors": highlighted_colors,
            "wireframe3D": wireframe_3d,
            "nonHighlightedColor": non_highlighted_color,
        }
        validated_params = HighlightElementsParameters(**params_dict)
        self._core.post_tapir_command(
            "HighlightElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return None

    def move_elements(self, elements_with_move_vectors: list[ElementsWithMoveVector]) -> MoveElementsResult:
        """
        Moves elements with a given vector.

        Args:
            elements_with_move_vectors (list[ElementsWithMoveVector]): The elements with move
                vector pairs.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elementsWithMoveVectors": elements_with_move_vectors,
        }
        validated_params = MoveElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "MoveElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return MoveElementsResult.model_validate(response_dict)

    def set_classifications_of_elements(
        self, element_classifications: list[ElementClassification]
    ) -> SetClassificationsOfElementsResult:
        """
        Sets the classifications of elements. In order to set the classification of an element
        to unclassified, omit the classificationItemId field. It works for subelements of
        hierarchal elements also.

        Args:
            element_classifications (list[ElementClassification]): A list of element
                classification identifiers.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elementClassifications": element_classifications,
        }
        validated_params = SetClassificationsOfElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "SetClassificationsOfElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return SetClassificationsOfElementsResult.model_validate(response_dict)

    def set_details_of_elements(self, elements_with_details: list[ElementsWithDetail]) -> SetDetailsOfElementsResult:
        """
        Sets the details of the given elements (floor, layer, order etc).

        Args:
            elements_with_details (list[ElementsWithDetail]): The elements with parameters.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elementsWithDetails": elements_with_details,
        }
        validated_params = SetDetailsOfElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "SetDetailsOfElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return SetDetailsOfElementsResult.model_validate(response_dict)

    def set_gdl_parameters_of_elements(
        self,
        elements_with_gdl_parameters: list[ElementsWithGDLParameter],
    ) -> SetGDLParametersOfElementsResult:
        """
        Sets the given GDL parameters of the given elements.

        Args:
            elements_with_gdl_parameters (list[ElementsWithGDLParameter]): The elements with GDL
                parameters dictionary pairs.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
        """
        params_dict = {
            "elementsWithGDLParameters": elements_with_gdl_parameters,
        }
        validated_params = SetGDLParametersOfElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "SetGDLParametersOfElements",
            validated_params.model_dump(by_alias=True, exclude_none=True),
        )
        return SetGDLParametersOfElementsResult.model_validate(response_dict)
