# This file is automatically generated by the build system.
# Do not edit this file directly.

from __future__ import annotations
from typing import TYPE_CHECKING
from pydantic import TypeAdapter

from multiconn_archicad.models.tapir.commands import (
    ConnectMEPElementsParameters,
    ConnectMEPElementsResult,
    CreateMEPElementsParameters,
    CreateMEPElementsResult,
    CreateMEPRoutingElementsParameters,
    CreateMEPRoutingElementsResult,
    GetMEPDistributionSystemsResult,
    GetMEPElementsParameters,
    GetMEPElementsResult,
    GetMEPPortsParameters,
    GetMEPPortsResult,
    GetMEPPreferenceTablesParameters,
    GetMEPPreferenceTablesResult,
    GetMEPRoutingElementsParameters,
    GetMEPRoutingElementsResult,
    ModifyMEPRoutingElementsParameters,
    ModifyMEPRoutingElementsResult,
)
from multiconn_archicad.models.tapir.types import (
    ElementIdArrayItem,
    ErrorItem,
    FailedExecutionResult,
    MEPConnectionData,
    MEPConnectionResult,
    MEPDistributionSystem,
    MEPDomains,
    MEPElement,
    MEPElementData,
    MEPElementPorts,
    MEPElementType,
    MEPPreferenceTable,
    MEPPreferenceTableDomain,
    MEPRoutingElementData,
    MEPRoutingElementDetails,
    MEPRoutingElementModificationData,
    SuccessfulExecutionResult,
)

if TYPE_CHECKING:
    from multiconn_archicad.core.core_commands import CoreCommands


class MepCommands:
    def __init__(self, core: CoreCommands):
        self._core = core

    def connect_mep_elements(self, connections_data: list[MEPConnectionData]) -> list[ErrorItem | MEPConnectionResult]:
        """
        Connects MEP routing elements to other MEP elements or routes. Merges routes, splits
        routes or creates branch elements as needed. Available from Archicad 28.

        Args:
            connections_data (list[MEPConnectionData]): Array of connections to create.

        Returns:
            list[ErrorItem | MEPConnectionResult]: A list of MEP connection results or errors.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        params_dict = {
            "connectionsData": connections_data,
        }
        validated_params = ConnectMEPElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "ConnectMEPElements", validated_params.model_dump(mode="json", by_alias=True, exclude_none=True)
        )
        validated_response = ConnectMEPElementsResult.model_validate(response_dict)
        return validated_response.connectionResults

    def create_mep_elements(self, elements_data: list[MEPElementData]) -> list[ElementIdArrayItem | ErrorItem]:
        """
        Creates MEP elements (Terminal, Accessory, Equipment or Fitting) at the given positions.
        Available from Archicad 28.

        Args:
            elements_data (list[MEPElementData]): Array of data to create MEP elements.

        Returns:
            list[ElementIdArrayItem | ErrorItem]: A list of element identifiers or errors.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        params_dict = {
            "elementsData": elements_data,
        }
        validated_params = CreateMEPElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "CreateMEPElements", validated_params.model_dump(mode="json", by_alias=True, exclude_none=True)
        )
        validated_response = CreateMEPElementsResult.model_validate(response_dict)
        return validated_response.elements

    def create_mep_routing_elements(
        self, routing_elements_data: list[MEPRoutingElementData]
    ) -> list[ElementIdArrayItem | ErrorItem]:
        """
        Creates MEP routing elements (duct, pipe or cable carrier routes) along the given
        polylines with optional cross section data and MEP system. Available from Archicad 28.

        Args:
            routing_elements_data (list[MEPRoutingElementData]): Array of data to create MEP
                routing elements.

        Returns:
            list[ElementIdArrayItem | ErrorItem]: A list of element identifiers or errors.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        params_dict = {
            "routingElementsData": routing_elements_data,
        }
        validated_params = CreateMEPRoutingElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "CreateMEPRoutingElements", validated_params.model_dump(mode="json", by_alias=True, exclude_none=True)
        )
        validated_response = CreateMEPRoutingElementsResult.model_validate(response_dict)
        return validated_response.elements

    def get_mep_distribution_systems(self) -> list[MEPDistributionSystem]:
        """
        Retrieves the MEP distribution systems of the project with their domain, MEP system
        attribute and member elements. Available from Archicad 28.

        Returns:
            list[MEPDistributionSystem]: The distribution systems of the project.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        response_dict = self._core.post_tapir_command("GetMEPDistributionSystems")
        validated_response = GetMEPDistributionSystemsResult.model_validate(response_dict)
        return validated_response.distributionSystems

    def get_mep_elements(
        self, element_types: None | list[MEPElementType] = None, domains: None | list[MEPDomains] = None
    ) -> list[MEPElement]:
        """
        Retrieves the MEP (Mechanical, Electrical, Plumbing) elements of the project, optionally
        filtered by type and domain. MEP elements are ordinary elements, so the generic element
        commands work on them as well (for example they can be deleted with the DeleteElements
        command). Available from Archicad 28.

        Args:
            element_types (None | list[MEPElementType]): Optional filter for the MEP element
                types.
            domains (None | list[MEPDomains]): Optional filter for the MEP domains.

        Returns:
            list[MEPElement]: The MEP elements.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        params_dict = {
            "elementTypes": element_types,
            "domains": domains,
        }
        validated_params = GetMEPElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "GetMEPElements", validated_params.model_dump(mode="json", by_alias=True, exclude_none=True)
        )
        validated_response = GetMEPElementsResult.model_validate(response_dict)
        return validated_response.elements

    def get_mep_ports(self, elements: list[ElementIdArrayItem]) -> list[ErrorItem | MEPElementPorts]:
        """
        Retrieves the ports of the given MEP elements including position, shape, size and
        connection status. Available from Archicad 28.

        Args:
            elements (list[ElementIdArrayItem]): A list of elements.

        Returns:
            list[ErrorItem | MEPElementPorts]: A list of MEP element ports or errors.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        params_dict = {
            "elements": elements,
        }
        validated_params = GetMEPPortsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "GetMEPPorts", validated_params.model_dump(mode="json", by_alias=True, exclude_none=True)
        )
        validated_response = GetMEPPortsResult.model_validate(response_dict)
        return validated_response.elementPorts

    def get_mep_preference_tables(self, domain: MEPPreferenceTableDomain) -> list[MEPPreferenceTable]:
        """
        Gets the circular cross section preference tables (referenceId, diameter, description)
        of the Piping or Ventilation domain. Available from Archicad 28.

        Args:
            domain (MEPPreferenceTableDomain)

        Returns:
            list[MEPPreferenceTable]: The circular segment preference tables of the domain.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        params_dict = {
            "domain": domain,
        }
        validated_params = GetMEPPreferenceTablesParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "GetMEPPreferenceTables", validated_params.model_dump(mode="json", by_alias=True, exclude_none=True)
        )
        validated_response = GetMEPPreferenceTablesResult.model_validate(response_dict)
        return validated_response.tables

    def get_mep_routing_elements(
        self, elements: list[ElementIdArrayItem]
    ) -> list[ErrorItem | MEPRoutingElementDetails]:
        """
        Retrieves the details of the given MEP routing elements: domain, MEP system, route
        polyline, segments with cross section data and nodes. Available from Archicad 28.

        Args:
            elements (list[ElementIdArrayItem]): A list of elements.

        Returns:
            list[ErrorItem | MEPRoutingElementDetails]: A list of MEP routing element details or
                errors.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        params_dict = {
            "elements": elements,
        }
        validated_params = GetMEPRoutingElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "GetMEPRoutingElements", validated_params.model_dump(mode="json", by_alias=True, exclude_none=True)
        )
        validated_response = GetMEPRoutingElementsResult.model_validate(response_dict)
        return validated_response.routingElements

    def modify_mep_routing_elements(
        self, routing_elements_data: list[MEPRoutingElementModificationData]
    ) -> list[FailedExecutionResult | SuccessfulExecutionResult]:
        """
        Modifies the given MEP routing elements: MEP system, cross section data of all segments
        and node positions. Available from Archicad 28.

        Args:
            routing_elements_data (list[MEPRoutingElementModificationData]): Array of data to
                modify MEP routing elements. Only provided fields are changed.

        Returns:
            list[FailedExecutionResult | SuccessfulExecutionResult]: A list of execution
                results.

        Raises:
            ArchicadAPIError: If the API returns an error response.
            RequestError: If there is a network or connection error.
            pydantic.ValidationError: If the parameters, or the API Response fail validation.
        """
        params_dict = {
            "routingElementsData": routing_elements_data,
        }
        validated_params = ModifyMEPRoutingElementsParameters(**params_dict)
        response_dict = self._core.post_tapir_command(
            "ModifyMEPRoutingElements", validated_params.model_dump(mode="json", by_alias=True, exclude_none=True)
        )
        validated_response = ModifyMEPRoutingElementsResult.model_validate(response_dict)
        return validated_response.executionResults
